# Generated by Django 5.2.4 on 2025-07-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('overview', models.TextField(blank=True, verbose_name='Sinopse')),
                ('genres', models.CharField(max_length=255, verbose_name='Gêneros')),
                ('vote_average', models.FloatField(default=0.0, verbose_name='Nota Média')),
                ('vote_count', models.IntegerField(default=0, verbose_name='Número de Votos')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Data de Lançamento')),
                ('popularity', models.FloatField(default=0.0, verbose_name='Popularidade')),
                ('runtime', models.IntegerField(blank=True, null=True, verbose_name='Duração (min)')),
                ('budget', models.BigIntegerField(blank=True, null=True, verbose_name='Orçamento')),
                ('revenue', models.BigIntegerField(blank=True, null=True, verbose_name='Receita')),
                ('original_language', models.CharField(default='en', max_length=10, verbose_name='Idioma Original')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
                'ordering': ['-vote_average', '-popularity'],
            },
        ),
    ]
